# Goal
int32 pan_deg           # si viene vacío, usa por defecto self.ptu_angles
int32 tilt_deg
#int32 tolerance_steps        # p.ej. 0
#float32 query_timeout_s      # p.ej. 10.0

---
# Result
bool success
string message

---
# Feedback
int32 current_pan_deg
int32 current_tilt_deg
string status