# Goal
#int32 pan_deg           # si viene vacío, usa por defecto self.ptu_angles
#int32 tilt_deg

# si viene vacío, usa por defecto self.ptu_angles
radar_msg/Ptu target_ptu

---
# Result
bool success
string message

---
# Feedback
int32 current_pan_deg
int32 current_tilt_deg
string status